---
when:
  - event: push
    branch: main
  - event: pull_request

matrix:
  nvim_version:
    - latest
    - 0.11

steps:
  - name: test
    image: anatolelucet/neovim:${nvim_version}-alpine
    commands:
      - apk add lua5.1 luarocks5.1 lua-busted
      - eval $(luarocks-5.1 path --no-bin)
      - busted
